package token

const (
	INVALID              = 1
	EOF                  = 1
	COMMENT              = 2
	TAG_OPEN             = 3
	TEXT                 = 4
	TAG_CLOSE            = 100
	TAG_MULTIPLICATION   = 102
	TAG_BRACKETOPEN      = 103
	TAG_BRACKETCLOSE     = 104
	TAG_PARENTHESISOPEN  = 105
	TAG_PARENTHESISCLOSE = 106
	TAG_DOUBLEDOT        = 107
	TAG_DOT              = 108
	TAG_WHITESPACE       = 109
	TAG_WORD             = 110
	TAG_NUMERIC          = 111
	TAG_EQUAL			 = 112
	TAG_STRING			 = 113
	TAG_END_OPEN		 = 114
	TAG_END_CLOSE		 = 115
)
var NAMES = map[int]string{
	EOF                  : "EOF",
	COMMENT              : "COMMENT",
	TAG_OPEN             : "TAG_OPEN",
	TEXT                 : "TEXT",
	TAG_CLOSE            : "TAG_CLOSE",
	TAG_MULTIPLICATION   : "TAG_MULTIPLICATION",
	TAG_BRACKETOPEN      : "TAG_BRACKETOPEN",
	TAG_BRACKETCLOSE     : "TAG_BRACKETCLOSE",
	TAG_PARENTHESISOPEN  : "TAG_PARENTHESISOPEN",
	TAG_PARENTHESISCLOSE : "TAG_PARENTHESISCLOSE",
	TAG_DOUBLEDOT        : "TAG_DOUBLEDOT",
	TAG_DOT              : "TAG_DOT",
	TAG_WHITESPACE       : "TAG_WHITESPACE",
	TAG_WORD             : "TAG_WORD",
	TAG_NUMERIC          : "TAG_NUMERIC",
	TAG_EQUAL			 : "TAG_EQUAL",
	TAG_STRING			 : "TAG_STRING",
	TAG_END_OPEN		 : "TAG_END_OPEN",
	TAG_END_CLOSE		 : "TAG_END_CLOSE",
}
