var NAMES = {};
var TAG = 1;
NAMES[TAG] = "TAG";
var VALUE = 2;
NAMES[VALUE] = "VALUE";
var ATTRKEY = 3;
NAMES[ATTRKEY] = "ATTRKEY";
var TAGCOMMENT = 4;
NAMES[TAGCOMMENT] = "TAGCOMMENT";
var DOCUMENT = 5;
NAMES[DOCUMENT] = "DOCUMENT";
var ATTR = 6;
NAMES[ATTR] = "ATTR";
module.exports = {
  TAG: TAG,
  VALUE: VALUE,
  ATTRKEY: ATTRKEY,
  TAGCOMMENT: TAGCOMMENT,
  DOCUMENT: DOCUMENT,
  ATTR: ATTR,
  NAMES: NAMES
};
//# sourceMappingURL=ast_const.js.map