var DOUBLEDOT = 58;
var GREATER = 60;
var MINOR = 62;
var EQUAL = 61;
var DOUBLEQUOTES = 34;
var MULTIPLICATION = 42;
var BRACKETOPEN = 91;
var BRACKETClOSE = 93;
var PARENTHESISOPEN = 40;
var PARENTHESISCLOSE = 41;
var BACKSLASH = 47;
var DOT = 46;
var BANG = 33;
var MINUS = 45;
var EOF = -1;
module.exports = {
  DOUBLEDOT: DOUBLEDOT,
  GREATER: GREATER,
  MINOR: MINOR,
  EQUAL: EQUAL,
  DOUBLEQUOTES: DOUBLEQUOTES,
  EOF: EOF,
  MULTIPLICATION: MULTIPLICATION,
  BRACKETOPEN: BRACKETOPEN,
  BRACKETClOSE: BRACKETClOSE,
  PARENTHESISOPEN: PARENTHESISOPEN,
  PARENTHESISCLOSE: PARENTHESISCLOSE,
  BACKSLASH: BACKSLASH,
  DOT: DOT,
  BANG: BANG,
  MINUS: MINUS
};
//# sourceMappingURL=char_const.js.map