from enum import Enum


class CharConst(Enum):
    DOUBLE_DOT = 58
    GREATER = 60
    MINOR = 62
    EQUAL = 61
    DOUBLE_QUOTES = 34
    MULTIPLICATION = 42
    BRACKET_OPEN = 91
    BRACKET_ClOSE = 93
    PARENTHESIS_OPEN = 40
    PARENTHESIS_CLOSE = 41
    BACKSLASH = 47
    DOT = 46
    BANG = 33
    MINUS = 45
    EOF = -1
    NAMES = {
        DOUBLE_DOT: "DOUBLE_DOT",
        GREATER: "GREATER",
        MINOR: "MINOR",
        EQUAL: "EQUAL",
        DOUBLE_QUOTES: "DOUBLE_QUOTES",
        MULTIPLICATION: "MULTIPLICATION",
        BRACKET_OPEN: "BRACKET_OPEN",
        BRACKET_ClOSE: "BRACKET_ClOSE",
        PARENTHESIS_OPEN: "PARENTHESIS_OPEN",
        PARENTHESIS_CLOSE: "PARENTHESIS_CLOSE",
        BACKSLASH: "BACKSLASH",
        DOT: "DOT",
        BANG: "BANG",
        MINUS: "MINUS",
        EOF: "EOF"
    }
